Validate email on blur
pxblue/react-native-workflows pull request #42
Opened 2020-12-17 19:34 UTC by daileytj

Fixes #38.

#### Changes proposed in this Pull Request:
- Validate email inputs on blur

2020-12-17 19:37 UTC, daileytj commented
Putting this up as a draft for now. 

I'm stuck on two things here:
- I can't figure out how to clean up the linting errors.
- The create account page's email input validation seems to be off by 1 character so a user can enter a valid email to enable the next button and delete 1 character making the email invalid but can still progress.

2020-12-29 14:14 UTC, joebochill requested changes
I think we can simplify this logic a little bit. Instead of having two useState values, we can just use a single boolean:
```
const [hasEmailFormatError, setHasEmailFormatError] = React.useState(false);
```

And then set it onBlur:
```
onBlur={(): void => {
    if(emailInput.length > 0 && !EMAIL_REGEX.test(emailInput)) setHasEmailFormatError(true);
}}
```

and unset it either onChange or onFocus (whichever is the desired behavior):
```
onChangeText={(text: string): void => {
    setEmailInput(text);
    setHasEmailFormatError(false);
}}
```

2020-12-29 14:16 UTC, joebochill commented
That should get you around any linting issues too.

2020-12-29 14:19 UTC, joebochill commented on login-workflow/src/subScreens/CreateAccount.tsx
> +            text ? props.onEmailChanged(text) : props.onEmailChanged(emailInput);
This is where the linting issue is. The ternary operator is usually used for variable assignment, not function calls like this. I would just use a simple if statement here:
```suggestion
            if( text){ props.onEmailChanged(text); }
            else { props.onEmailChanged(emailInput); }
```

2021-01-05 19:21 UTC, joebochill approved these changes

2021-01-05 20:49 UTC, merged