Feature/custom registration
pxblue/react-native-workflows pull request #46
Opened 2021-03-17 17:49 UTC by joebochill

For PXBLUE-XXXX
Fixes #40 
Fixes #39 

#### Changes proposed in this Pull Request:
- Add the ability to inject custom forms into registration
- Clean up form submission on Enter/Submit/Done
- Update documentation

2021-03-18 17:40 UTC, emclaug2 requested changes
The custom account details forms look good to me, one thing I noticed is that in the `Create Account` workflow, the entered email is disregarded at the end.

![image](https://user-images.githubusercontent.com/6538289/111671649-8a2bec80-87ef-11eb-8029-6f4f5e41e51f.png)

2021-03-18 18:45 UTC, joebochill commented
> The custom account details forms look good to me, one thing I noticed is that in the `Create Account` workflow, the entered email is disregarded at the end.

This information actually comes from the user's implementation of the Registration actions. In the final call to complete registration, they need to return back an object with the details of the account (this is because it's generic enough to handle invite registration or self registration, so WE might not know the email address that was registered):

https://github.com/pxblue/react-native-workflows/blob/feature/custom-registration/login-workflow/example/src/actions/RegistrationUIActions.tsx#L93

I can change it in the demo so it makes more sense, but ultimately it's up the the end user to provide that information.

2021-03-18 21:33 UTC, emclaug2 commented
I'm going to approve this PR since I didn't notice anything related to the account details customization.

2021-03-18 21:33 UTC, emclaug2 approved these changes

2021-03-19 12:53 UTC, jeffvg commented
does loginAction have props to display 'Log In With Google'

2021-03-19 13:19 UTC, joebochill commented
> does loginAction have props to display 'Log In With Google'
> 
> ok just JSX.element?

It's just JSX.Element so the user can pass in any content they want. If they want a google button, they pass in a google button, if they want a facebook button, they pass in a facebook button, etc.

2021-03-19 13:20 UTC, jeffvg commented
> > does loginAction have props to display 'Log In With Google'
> > ok just JSX.element?
> 
> It's just JSX.Element so the user can pass in any content they want. If they want a google button, they pass in a google button, if they want a facebook button, they pass in a facebook button, etc.

ok maybe we can go over this later. I have this right now...
Property 'loginActions' does not exist on type 'AuthUIContextProviderProps'

2021-03-19 13:53 UTC, jeffvg commented on login-workflow/example/App.tsx
> +                { title: 'CustomTitle', instructions: 'Get your details in yo', component: CustomAccountDetailsTwo },
Looks like instructions: needs updated

2021-03-20 15:52 UTC, merged