React Native workflow fixes
pxblue/react-native-workflows pull request #91
Opened 2021-07-20 17:04 UTC by daileytj

Fixes PXBLUE-2285, #83, and #90.

#### Changes proposed in this Pull Request:
- Allow users to go back during all steps in the account registration
- Changed EULA page order so it shows first during self registration
- Add ability to customize character limits for first and last name text fields
- Clear Invalid credentials error message after editing input

#### To Test:
- Custom character limit, uncomment the registrationConfig definition in the `AuthUIContextProvider` in the example project's `App.tsx` file.

- Invalid credentials error message, edit the example project's `AuthUIActions.tsx `login method to immediately return `throw new Error('LOGIN.INVALID_CREDENTIALS');`. Start up example project and try to login. The "Invalid credentials" error should display on the email and password inputs. Modify either input and observe the error being removed until submitting and receiving another transit error.

waiting for: https://github.com/pxblue/react-auth-shared/pull/36 and react-auth-shared publish.

2021-07-20 21:48 UTC, joebochill requested changes
See the comments on the React PR...they are all applicable here as well (except I was able to run the demo without any hubbub).

2021-07-22 13:49 UTC, joebochill approved these changes
Looks good, just have the same question about the cancel label for @huayunh

2021-07-22 13:49 UTC, joebochill commented on login-workflow/example/ios/example/AppDelegate.m
> +
What's this?

2021-07-22 13:52 UTC, daileytj commented on login-workflow/example/ios/example/AppDelegate.m
> +
I was getting a "RCTBridge required dispatch_sync to load RCTDevLoadingView" error locally so I fixed it with this.

Not entirely sure how it works, just copy/past from here: https://stackoverflow.com/questions/45988103/rctbridge-required-dispatch-sync-to-load-rctdevloadingview-this-may-lead-to-dea/48903673

2021-07-22 14:27 UTC, joebochill commented on login-workflow/example/ios/example/AppDelegate.m
> +
Nice, we've been seeing those pop up on a couple of our projects...interesting to see it's related react-navigation

2021-07-22 14:27 UTC, joebochill commented
(and make sure the submodule is pointing back to latest dev)

2021-07-22 17:58 UTC, merged